url: https://yasith.dev
title: Yasith Jayawardana
description: >-
  PhD student at [@oduwsdl](https://twitter.com/@oduwsdl) [@nirdslab](https://twitter.com/@nirdslab), Interned at [@wso2](https://twitter.com/@wso2), [@apache](https://twitter.com/@apache) contributor
header_pages:
  - education.html
  - experience.html
  - projects.html
  - publications.html

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima